affected:
- package:
    ecosystem: PyPI
    name: patchelf
    purl: pkg:pypi/patchelf
  ranges:
  - events:
    - introduced: '0'
    type: ECOSYSTEM
  versions:
  - 0.11.0.0
  - 0.12.0.0
  - 0.13.0.0
  - 0.13.1.0
  - 0.14.0.0
  - 0.14.1.0
  - 0.14.2.0
  - 0.14.3.0
  - 0.14.5.0
  - 0.15.0.0
  - 0.16.1.0
  - 0.17.0.0
  - 0.17.2.0
  - 0.17.2.1
  - 0.18.0.0
aliases:
- CVE-2022-44940
details: Patchelf v0.9 was discovered to contain an out-of-bounds read via the function
  modifyRPath at src/patchelf.cc.
id: PYSEC-2022-43144
modified: '2024-11-21T14:22:58.452456Z'
published: '2022-12-19T22:15:00Z'
references:
- type: EVIDENCE
  url: https://github.com/NixOS/patchelf/pull/419
- type: FIX
  url: https://github.com/NixOS/patchelf/pull/419
- type: WEB
  url: https://github.com/NixOS/patchelf/pull/419
severity:
- score: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:H
  type: CVSS_V3
withdrawn: '2024-11-22T04:37:04Z'
