id: PYSEC-0000-CVE-2024-53908
details: An issue was discovered in Django 5.1 before 5.1.4, 5.0 before 5.0.10, and
  4.2 before 4.2.17. Direct usage of the django.db.models.fields.json.HasKey lookup,
  when an Oracle database is used, is subject to SQL injection if untrusted data is
  used as an lhs value. (Applications that use the jsonfield.has_key lookup via __
  are unaffected.)
affected:
- package:
    name: django
    ecosystem: PyPI
    purl: pkg:pypi/django
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "5.1"
    - fixed: 5.1.4
    - introduced: "5.0"
    - fixed: 5.0.10
    - introduced: "4.2"
    - fixed: 4.2.17
references:
- type: WEB
  url: https://docs.djangoproject.com/en/dev/releases/security/
- type: WEB
  url: https://groups.google.com/g/django-announce
- type: WEB
  url: https://www.openwall.com/lists/oss-security/2024/12/04/3
aliases:
- CVE-2024-53908
modified: "2024-12-06T17:15:12Z"
published: "2024-12-06T12:15:18Z"
