id: PYSEC-0000-CVE-2024-56374
details: An issue was discovered in Django 5.1 before 5.1.5, 5.0 before 5.0.11, and
  4.2 before 4.2.18. Lack of upper-bound limit enforcement in strings passed when
  performing IPv6 validation could lead to a potential denial-of-service attack. The
  undocumented and private functions clean_ipv6_address and is_valid_ipv6_address
  are vulnerable, as is the django.forms.GenericIPAddressField form field. (The django.db.models.GenericIPAddressField
  model field is not affected.)
affected:
- package:
    name: django
    ecosystem: PyPI
    purl: pkg:pypi/django
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "5.1"
    - fixed: 5.1.5
    - introduced: "5.0"
    - fixed: 5.0.11
    - introduced: "4.2"
    - fixed: 4.2.18
references:
- type: ARTICLE
  url: https://www.djangoproject.com/weblog/2025/jan/14/security-releases/
- type: WEB
  url: https://docs.djangoproject.com/en/dev/releases/security/
- type: WEB
  url: https://groups.google.com/g/django-announce
- type: WEB
  url: http://www.openwall.com/lists/oss-security/2025/01/14/2
aliases:
- CVE-2024-56374
modified: "2025-01-14T19:15:32Z"
published: "2025-01-14T19:15:32Z"
