affected:
- package:
    ecosystem: PyPI
    name: exiv2
    purl: pkg:pypi/exiv2
  ranges:
  - events:
    - introduced: '0'
    type: ECOSYSTEM
  versions:
  - '0.1'
  - 0.11.0
  - 0.11.1
  - 0.11.2
  - 0.11.3
  - 0.12.0
  - 0.12.1
  - 0.13.0
  - 0.13.1
  - 0.13.2
  - 0.14.0
  - 0.14.1
  - 0.15.0
  - 0.16.0
  - 0.16.1
  - 0.16.2
  - 0.16.2.post1
  - 0.16.3
  - 0.16.3.post1
  - 0.17.0
  - 0.17.1
  - '0.2'
  - '0.3'
  - 0.3.1
aliases:
- CVE-2017-9953
details: There is an invalid free in Image::printIFDStructure that leads to a Segmentation
  fault in Exiv2 0.26. A crafted input will lead to a remote denial of service attack.
id: PYSEC-2017-142
modified: '2024-11-21T14:22:47.877232Z'
published: '2017-06-26T23:29:00Z'
references:
- type: EVIDENCE
  url: https://bugzilla.redhat.com/show_bug.cgi?id=1465061
- type: REPORT
  url: https://bugzilla.redhat.com/show_bug.cgi?id=1465061
- type: ADVISORY
  url: https://bugzilla.redhat.com/show_bug.cgi?id=1465061
severity:
- score: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H
  type: CVSS_V3
withdrawn: '2024-11-22T04:37:04Z'
