id: PYSEC-0000-CVE-2018-10998
severity:
- type: CVSS_V3
  score: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
details: An issue was discovered in Exiv2 0.26. readMetadata in jp2image.cpp allows
  remote attackers to cause a denial of service (SIGABRT) by triggering an incorrect
  Safe::add call.
affected:
- package:
    name: exiv2
    ecosystem: PyPI
    purl: pkg:pypi/exiv2
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "0"
references:
- type: EVIDENCE
  url: https://github.com/Exiv2/exiv2/issues/303
- type: REPORT
  url: https://github.com/Exiv2/exiv2/issues/303
- type: ARTICLE
  url: https://lists.debian.org/debian-lts-announce/2018/06/msg00010.html
- type: WEB
  url: https://lists.debian.org/debian-lts-announce/2018/06/msg00010.html
- type: ADVISORY
  url: https://www.debian.org/security/2018/dsa-4238
- type: WEB
  url: https://usn.ubuntu.com/3700-1/
- type: ADVISORY
  url: https://security.gentoo.org/glsa/201811-14
- type: ADVISORY
  url: https://access.redhat.com/errata/RHSA-2019:2101
aliases:
- CVE-2018-10998
modified: "2023-03-01T17:13:00Z"
published: "2018-05-12T04:29:00Z"
