id: PYSEC-0000-CVE-2019-14370
severity:
- type: CVSS_V3
  score: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
details: In Exiv2 0.27.99.0, there is an out-of-bounds read in Exiv2::MrwImage::readMetadata()
  in mrwimage.cpp. It could result in denial of service.
affected:
- package:
    name: exiv2
    ecosystem: PyPI
    purl: pkg:pypi/exiv2
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "0"
references:
- type: EVIDENCE
  url: https://github.com/Exiv2/exiv2/issues/954
- type: REPORT
  url: https://github.com/Exiv2/exiv2/issues/954
- type: ARTICLE
  url: https://lists.debian.org/debian-lts-announce/2023/01/msg00004.html
- type: WEB
  url: https://lists.debian.org/debian-lts-announce/2023/01/msg00004.html
aliases:
- CVE-2019-14370
modified: "2023-01-13T16:19:00Z"
published: "2019-07-28T19:15:00Z"
