id: PYSEC-0000-CVE-2018-9145
severity:
- type: CVSS_V3
  score: CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
details: 'In the DataBuf class in include/exiv2/types.hpp in Exiv2 0.26, an issue
  exists in the constructor with an initial buffer size. A large size value may lead
  to a SIGABRT during an attempt at memory allocation. NOTE: some third parties have
  been unable to reproduce the SIGABRT when using the 4-DataBuf-abort-1 PoC file.'
affected:
- package:
    name: exiv2
    ecosystem: PyPI
    purl: pkg:pypi/exiv2
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "0"
references:
- type: EVIDENCE
  url: https://github.com/xiaoqx/pocs/tree/master/exiv2
- type: WEB
  url: https://github.com/xiaoqx/pocs/tree/master/exiv2
- type: REPORT
  url: https://bugzilla.redhat.com/show_bug.cgi?id=1564281
- type: REPORT
  url: https://bugzilla.novell.com/show_bug.cgi?id=1087879
- type: ADVISORY
  url: https://security.gentoo.org/glsa/201811-14
aliases:
- CVE-2018-9145
modified: "2019-03-27T19:23:00Z"
published: "2018-03-30T08:29:00Z"
