id: PYSEC-0000-CVE-2023-49080
severity:
- type: CVSS_V3
  score: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N
details: The Jupyter Server provides the backend (i.e. the core services, APIs, and
  REST endpoints) for Jupyter web applications like Jupyter notebook, JupyterLab,
  and Voila. Unhandled errors in API requests coming from an authenticated user include
  traceback information, which can include path information. There is no known mechanism
  by which to trigger these errors without authentication, so the paths revealed are
  not considered particularly sensitive, given that the requesting user has arbitrary
  execution permissions already in the same environment. A fix has been introduced
  in commit `0056c3aa52` which no longer includes traceback information in JSON error
  responses. For compatibility, the traceback field is present, but always empty.
  This commit has been included in version 2.11.2. Users are advised to upgrade. There
  are no known workarounds for this vulnerability.
affected:
- package:
    name: jupyter-server
    ecosystem: PyPI
    purl: pkg:pypi/jupyter-server
  ranges:
  - type: GIT
    repo: https://github.com/jupyter-server/jupyter_server
    events:
    - introduced: "0"
    - fixed: 0056c3aa52cbb28b263a7a609ae5f17618b36652
  - type: ECOSYSTEM
    events:
    - introduced: "0"
    - fixed: 2.11.2
references:
- type: ADVISORY
  url: https://github.com/jupyter-server/jupyter_server/security/advisories/GHSA-h56g-gq9v-vc8r
- type: FIX
  url: https://github.com/jupyter-server/jupyter_server/commit/0056c3aa52cbb28b263a7a609ae5f17618b36652
- type: WEB
  url: https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/62LO7PPIAMLIDEKUOORXLHKLGA6QPL77/
- type: WEB
  url: https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FG2JWZI5KPUYMDPS53AIFTZJWZD3IT6I/
aliases:
- CVE-2023-49080
- GHSA-h56g-gq9v-vc8r
modified: "2023-12-14T03:15:00Z"
published: "2023-12-04T21:15:00Z"
