id: PYSEC-0000-CVE-2018-7206
severity:
- type: CVSS_V3
  score: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H
details: An issue was discovered in Project Jupyter JupyterHub OAuthenticator 0.6.x
  before 0.6.2 and 0.7.x before 0.7.3. When using JupyterHub with GitLab group whitelisting
  for access control, group membership was not checked correctly, allowing members
  not in the whitelisted groups to create accounts on the Hub. (Users were not allowed
  to access other users' accounts, but could create their own accounts on the Hub
  linked to their GitLab account. GitLab authentication not using gitlab_group_whitelist
  is unaffected. No other Authenticators are affected.)
affected:
- package:
    name: jupyterhub
    ecosystem: PyPI
    purl: pkg:pypi/jupyterhub
  ranges:
  - type: GIT
    repo: https://github.com/jupyterhub/oauthenticator
    events:
    - introduced: "0"
    - fixed: 1845c0e4b1bff3462c91c3108c85205acd3c75a2
  - type: ECOSYSTEM
    events:
    - introduced: "0"
references:
- type: ARTICLE
  url: https://blog.jupyter.org/security-fix-for-jupyterhub-gitlab-oauthenticator-7b14571d1f76
- type: FIX
  url: https://github.com/jupyterhub/oauthenticator/commit/1845c0e4b1bff3462c91c3108c85205acd3c75a2
- type: WEB
  url: https://github.com/jupyterhub/oauthenticator/blob/8499dc2/CHANGELOG.md#073---2018-02-16
- type: ADVISORY
  url: https://github.com/jupyterhub/oauthenticator/blob/8499dc2/CHANGELOG.md#073---2018-02-16
aliases:
- CVE-2018-7206
modified: "2021-01-13T14:52:00Z"
published: "2018-02-18T03:29:00Z"
