id: PYSEC-0000-CVE-2024-21543
details: Versions of the package djoser before 2.3.0 are vulnerable to Authentication
  Bypass when the authenticate() function fails. This is because the system falls
  back to querying the database directly, granting access to users with valid credentials,
  and eventually bypassing custom authentication checks such as two-factor authentication,
  LDAP validations, or requirements from configured AUTHENTICATION_BACKENDS.
affected:
- package:
    name: djoser
    ecosystem: PyPI
    purl: pkg:pypi/djoser
  ranges:
  - type: GIT
    repo: https://github.com/sunscrapers/djoser
    events:
    - introduced: "0"
    - fixed: d33c3993c0c735f23cbedc60fa59fce69354f19d
  - type: ECOSYSTEM
    events:
    - introduced: "0"
    - fixed: 2.3.0
references:
- type: FIX
  url: https://github.com/sunscrapers/djoser/commit/d33c3993c0c735f23cbedc60fa59fce69354f19d
- type: REPORT
  url: https://github.com/sunscrapers/djoser/issues/795
- type: WEB
  url: https://github.com/sunscrapers/djoser/pull/819
- type: WEB
  url: https://github.com/sunscrapers/djoser/releases/tag/2.3.0
- type: WEB
  url: https://security.snyk.io/vuln/SNYK-PYTHON-DJOSER-8366540
aliases:
- CVE-2024-21543
modified: "2024-12-13T20:15:19Z"
published: "2024-12-13T05:15:07Z"
